name: flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.9
  flutter_localizations:
    sdk: flutter 
  intl: ^0.20.2
  firebase_auth: ^6.4.0
  google_sign_in: ^6.2.1 
  firebase_core: ^4.7.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.3
  cloud_firestore: ^6.4.1
  shared_preferences: ^2.5.4 # Movido para cá (produção)
  vibration: ^2.0.0           # Movido para cá e adicionada a versão correta
  geocoding: ^4.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
flutter:
  assets:
    - assets/images/
     
  uses-material-design: true